# Generated by Django 4.2.3 on 2023-08-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('email', models.EmailField(max_length=75)),
                ('shirt_size', models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large')], max_length=1)),
            ],
        ),
    ]
