# Generated by Django 4.2.3 on 2023-08-09 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Class_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='Person',
        ),
    ]
